/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2018-04-23 03:38:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.page.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.neusoft.core.util.PCache;

public final class frontIndex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/page/common/commonPage.jsp", Long.valueOf(1470807506000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String resourcesUrl = PCache.getHM().get("website.resources.url");
	String contextName = request.getContextPath();
	String resourcesDir = "/resources";
	String websiteVersion = PCache.getHM().get("website.version");
	String websiteName = PCache.getHM().get("website.name");

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/page/common/commonPage.jsp(16,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("base");
      // /WEB-INF/page/common/commonPage.jsp(16,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(contextName);
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/page/common/commonPage.jsp(18,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("resourcesUrl");
      // /WEB-INF/page/common/commonPage.jsp(18,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(resourcesUrl + contextName + resourcesDir);
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/page/common/commonPage.jsp(21,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("version");
      // /WEB-INF/page/common/commonPage.jsp(21,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(System.currentTimeMillis());
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent(null);
      // /WEB-INF/page/common/commonPage.jsp(23,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setVar("websiteName");
      // /WEB-INF/page/common/commonPage.jsp(23,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setValue(websiteName);
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><!--ie使用edge渲染模式-->\r\n");
      out.write("<meta content=\"width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no\" id=\"viewport\" name=\"viewport\">\r\n");
      out.write("<meta name=\"renderer\" content=\"webkit\"><!--360渲染模式-->\r\n");
      out.write("<meta name=\"format-detection\" content=\"telephone=notelphone=no, email=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("<meta name=\"apple-touch-fullscreen\" content=\"yes\"/><!-- 是否启用 WebApp 全屏模式，删除苹果默认的工具栏和菜单栏 -->\r\n");
      out.write("<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\"/><!-- 设置苹果工具栏颜色:默认值为 default，可以定为 black和 black-translucent-->\r\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"no-siteapp\" /><!-- 不让百度转码 -->\r\n");
      out.write("<meta name=\"HandheldFriendly\" content=\"true\"><!-- 针对手持设备优化，主要是针对一些老的不识别viewport的浏览器，比如黑莓 -->\r\n");
      out.write("<meta name=\"MobileOptimized\" content=\"320\"><!-- 微软的老式浏览器 -->\r\n");
      out.write("<meta name=\"screen-orientation\" content=\"portrait\"><!-- uc强制竖屏 -->\r\n");
      out.write("<meta name=\"x5-orientation\" content=\"portrait\"><!-- QQ强制竖屏 -->\r\n");
      out.write("<meta name=\"browsermode\" content=\"application\"><!-- UC应用模式 -->\r\n");
      out.write("<meta name=\"x5-page-mode\" content=\"app\"><!-- QQ应用模式 -->\r\n");
      out.write("<meta name=\"msapplication-tap-highlight\" content=\"no\"><!-- windows phone 点击无高光 -->\r\n");
      out.write("<title>大连意匠装饰工程有限公司</title>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/frontcss/bootstrap.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<!-- jQuery (necessary JavaScript plugins) -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/frontjs/jquery.min.js\"></script>\r\n");
      out.write("<!-- Custom Theme files -->\r\n");
      out.write("<!--  -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/frontcss/style.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<!-- banner 滑动 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/frontcss/silder.css\" />\r\n");
      out.write("<!--<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/frontcss/fonts/font-awesome/css/font-awesome.min.css\">-->\r\n");
      out.write("\t<link href=\"//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Custom Theme files -->\r\n");
      out.write("<!-- START gallery -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/components/dist/stylesheets/chromagallery.css\">\r\n");
      out.write("<!-- END gallery -->\r\n");
      out.write("<!--//theme style-->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- header -->\r\n");
      out.write("<div id=\"home\" class=\"top-banner\">\r\n");
      out.write("\t <div class=\"header\">\r\n");
      out.write("\t\t <div class=\"container\">\r\n");
      out.write("\t\t\t <div class=\"headr-left\">\r\n");
      out.write("\t\t\t\t <div class=\"details\">\r\n");
      out.write("\t\t\t\t\t <ul>\r\n");
      out.write("\t\t\t\t\t\t<!--  <li><a href=\"mailto:@example.com\"><span class=\"glyphicon glyphicon-envelope\" aria-hidden=\"true\"></span>info(at)example.com</a></li> -->\r\n");
      out.write("\t\t\t\t\t\t <li><i class=\"fa fa-phone\"></i>18525511611</li>\r\n");
      out.write("\t\t\t\t\t </ul>\r\n");
      out.write("\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t <div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t\t <div class=\"headr-right\">\r\n");
      out.write("\t\t\t\t <!-- <div class=\"social\">\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"facebook\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"twitter\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"dribble\"></i></a>\t\r\n");
      out.write("\t\t\t     </div>\t\t -->\t\t \r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t\t <div class=\"clearfix\"></div>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t </div>\r\n");
      out.write("</div>\t\r\n");
      out.write("<!---->\r\n");
      out.write("<div class=\"top-header\">\r\n");
      out.write("\t <div class=\"container\">\t\r\n");
      out.write("\t\t <div class=\"logo\">\r\n");
      out.write("\t\t\t <h1><a href=\"#\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;意匠</a></h1>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t\t <div class=\"top-menu\">\r\n");
      out.write("\t\t\t  <nav class=\"cl-effect-1\">\r\n");
      out.write("\t\t\t <span class=\"menu\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/menu.png\" alt=\"\"/></span>\r\n");
      out.write("\t\t\t <ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"index.html\">首页</a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"scroll\" href=\"#about\">关于我们</a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"scroll\" href=\"#service\">服务</a></li>\t\t\t\t\r\n");
      out.write("\t\t\t\t<li><a class=\"scroll\" href=\"#gallery\">装修展示</a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"scroll\" href=\"#testi\">全包套餐</a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"scroll\" href=\"#contact\">联系我们</a></li>\r\n");
      out.write("\t\t\t </ul>\r\n");
      out.write("\t\t\t </nav>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t </div>\r\n");
      out.write("</div>\t\r\n");
      out.write("<!---->\r\n");
      out.write("<!-- <div class=\"banner\">\r\n");
      out.write("\t <div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"banner-info\">\r\n");
      out.write("\t\t\t\t <h2>Lorem ipsum dolor consectetur adipiscing elit.</h2>\r\n");
      out.write("\t\t\t\t <h3>Aenean dictum accumsan tincidunt.</h3>\r\n");
      out.write("\t\t\t\t <a href=\"#\">Click</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t </div>\r\n");
      out.write("</div> -->\r\n");
      out.write("<div class=\"js-silder\">\r\n");
      out.write("      <div class=\"silder-scroll\">\r\n");
      out.write("           <div class=\"silder-main\">\r\n");
      out.write("               <div class=\"silder-main-img\">\r\n");
      out.write("                   <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/silder/banner1.jpg\" alt=\"\">\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"silder-main-img\">\r\n");
      out.write("                   <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/silder/banner2.jpg\" alt=\"\">\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"silder-main-img\">\r\n");
      out.write("                   <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/silder/banner3.jpg\" alt=\"\">\r\n");
      out.write("               </div>\r\n");
      out.write("           </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"js-silder-ctrl\"></div>\r\n");
      out.write("   </div>\r\n");
      out.write("<!---->\r\n");
      out.write("<div class=\"copyrights\">公司简介</div>\r\n");
      out.write("<div id=\"about\" class=\"welcome\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t <div class=\"welcm-grids\">\r\n");
      out.write("\t\t\t <div class=\"col-md-6 welcm-left\">\r\n");
      out.write("\t\t\t\t <h3>公司简介</h3>\r\n");
      out.write("\t\t\t\t <h4>大连意匠装饰工程有限公司</h4>\r\n");
      out.write("\t\t\t\t <p>本公司主要从事经营：家装、别墅、二手房翻新改造、商场、店铺、饭店、酒店、展厅、幼儿园、写字楼、办公室及绿化园林等装修设计与工程施工。施工人员经验丰富，施工队伍稳定，且有完善的售后服务体系免去客户后顾之忧。 </p>\r\n");
      out.write("\t\t\t\t <p class=\"text\">透明化的预算方式，绿色健康的施工技艺，严格的质量监督体系赢得了业内人士的一致赞誉和广大客户的普遍信赖，全体员工一直秉承“以品质求生存，以信誉求发展”的经营理念，始终坚持以客户的需求和满意为核心，以“诚信”为宗旨，不断用优质、精美、具有创造力的空间装饰产品为客户提供更大的价值回报。致力于追求信誉、品质、服务与价格的完美比例。</p>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t\t <div class=\"col-md-6 welcm-right\">\r\n");
      out.write("\t\t\t\t <!-- <h3>Etiam aliquam arcu vitae maximus.</h3> -->\r\n");
      out.write("\t\t\t\t <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/bnr2.jpg\" class=\"img-responsive\" alt=\"\"/>\r\n");
      out.write("\t\t\t\t <!-- <p>Mauris non suscipit mi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed eros felis, faucibus ut dui sed, volutpat auctor nibh. Fusce ornare urna id risus dignissim luctus.</p> -->\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t\t <div class=\"clearfix\"></div>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!---->\r\n");
      out.write("\r\n");
      out.write("<div id=\"service\" class=\"services\">\r\n");
      out.write("\t <div class=\"container\">\r\n");
      out.write("\t \t\r\n");
      out.write("\t \t<div style=\"position: relative;\" style=\"width:100%;height:100%;\">\r\n");
      out.write("\t \t\t<span style=\"position: absolute;top:40%;left:6%;width: 12%;height:51%;cursor: pointer;\" onclick=\"window.open('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${base}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/front/index');\"></span>\r\n");
      out.write("\t \t\t<span style=\"position: absolute;top:40%;left:22%;width: 12%;height:51%;cursor: pointer;\" onclick=\"window.open('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${base}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/front/index');\"></span>\r\n");
      out.write("\t \t\t<span style=\"position: absolute;top:40%;left:37%;width: 12%;height:51%;cursor: pointer;\" onclick=\"window.open('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${base}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/front/index');\"></span>\r\n");
      out.write("\t \t\t<span style=\"position: absolute;top:40%;left:52%;width: 12%;height:51%;cursor: pointer;\" onclick=\"window.open('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${base}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/front/index');\"></span>\r\n");
      out.write("\t \t\t<span style=\"position: absolute;top:40%;left:67%;width: 12%;height:51%;cursor: pointer;\" onclick=\"window.open('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${base}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/front/index');\"></span>\r\n");
      out.write("\t \t\t<span style=\"position: absolute;top:40%;left:83%;width: 12%;height:51%;cursor: pointer;\" onclick=\"window.open('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${base}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/front/index');\"></span>\r\n");
      out.write("\t \t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/FUWU.jpg\">\r\n");
      out.write("\t \t</div>\r\n");
      out.write("\t\t<!--  <h3>服务</h3>\r\n");
      out.write("\t\t <div class=\"specialty-grids-top\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 service-box\" style=\"visibility: visible; -webkit-animation-delay: 0.4s;\">\r\n");
      out.write("\t\t\t\t\t<figure class=\"icon\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"glyphicon3 glyphicon-edit\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t<h5>工程保障</h5>\r\n");
      out.write("\t\t\t\t\t<p>工程保障 工程保障工程保障工程 工程保障 工程保障 工程保障 工程保障 工程保障 工程保障保障工程保障</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 service-box wow bounceIn animated\" data-wow-delay=\"0.4s\" style=\"visibility: visible; -webkit-animation-delay: 0.4s;\">\r\n");
      out.write("\t\t\t\t\t<figure class=\"icon\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"glyphicon3 glyphicon-leaf\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t<h5>服务流程</h5>\r\n");
      out.write("\t\t\t\t\t<p>服务流程>服务流程>服务流程>服务流程>服务流程>服务流程</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 service-box wow bounceIn animated\" data-wow-delay=\"0.4s\" style=\"visibility: visible; -webkit-animation-delay: 0.4s;\">\r\n");
      out.write("\t\t\t\t\t<figure class=\"icon\">\r\n");
      out.write("\t\t\t\t\t\t <span class=\"glyphicon3 glyphicon-hourglass\" aria-hidden=\"true\"></span>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t<h5>设计优先</h5>\r\n");
      out.write("\t\t\t\t\t<p>设计优先设计优先设计优先设计优先设计优先设计优先.设计优先设计优先设计优先设计优先</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t </div> -->\r\n");
      out.write("\t </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- gallery -->\r\n");
      out.write("<div id=\"gallery\" class=\"gallery-top\">\r\n");
      out.write("  \t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"gallery-info\">\r\n");
      out.write("\t\t\t\t\t<h3>装修展示</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chroma-gallery mygallery\">\r\n");
      out.write("\t\t\t\t    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/1.jpg\" alt=\"\" data-largesrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/1.jpg\">\r\n");
      out.write("\t\t\t\t    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/2.jpg\" alt=\"\" data-largesrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/2.jpg\">\r\n");
      out.write("\t\t\t\t    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/3.jpg\" alt=\"\" data-largesrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/3.jpg\">\r\n");
      out.write("\t\t\t\t    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/4.jpg\" alt=\"\" data-largesrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/4.jpg\">\r\n");
      out.write("\t\t\t\t    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/5.jpg\" alt=\"\" data-largesrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/5.jpg\">\r\n");
      out.write("\t\t\t\t    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/6.jpg\" alt=\"\" data-largesrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/6.jpg\">\r\n");
      out.write("\t\t\t\t    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/7.jpg\" alt=\"\" data-largesrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/7.jpg\">\r\n");
      out.write("\t\t\t\t    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/8.jpg\" alt=\"\" data-largesrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/8.jpg\">\r\n");
      out.write("\t\t\t\t    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/9.jpg\" alt=\"\" data-largesrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/9.jpg\">\r\n");
      out.write("\t\t\t\t    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/10.jpg\" alt=\"\" data-largesrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/10.jpg\">\r\n");
      out.write("\t\t\t\t    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/11.jpg\" alt=\"\" data-largesrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/11.jpg\">\r\n");
      out.write("\t\t\t\t    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/12.jpg\" alt=\"\" data-largesrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/12.jpg\">\r\n");
      out.write("\t\t\t\t    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/13.jpg\" alt=\"\" data-largesrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/13.jpg\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"testi\" class=\"testimonal\">\r\n");
      out.write("\t <div class=\"container\">\r\n");
      out.write("\t\t <div class=\"testi-top\">\r\n");
      out.write("\t\t\t <h3>全包套餐</h3>\r\n");
      out.write("\t\t\t<div style=\"display:block;width: 100%;height: 400px;\">\r\n");
      out.write("\t\t\t \t<span style=\"display:inline-block;background-color:#004D60;width: 30%;height:90%;cursor: pointer;\" onclick=\"window.open('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${base}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/front/index');\">\r\n");
      out.write("\t\t\t \t\t全包\r\n");
      out.write("\t\t\t \t</span>\r\n");
      out.write("\t\t \t\t<span style=\"display:inline-block;background-color:#004D60;width: 30%;height:90%;cursor: pointer;\" onclick=\"window.open('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${base}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/front/index');\">\r\n");
      out.write("\t\t \t\t\t半包\r\n");
      out.write("\t\t \t\t</span>\r\n");
      out.write("\t\t \t\t<span style=\"display:inline-block;background-color:#004D60;width: 30%;height:90%;cursor: pointer;\" onclick=\"window.open('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${base}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/front/index');\">\r\n");
      out.write("\t\t \t\t\t大包\r\n");
      out.write("\t\t \t\t</span>\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!---->\r\n");
      out.write("<!--team-->\r\n");
      out.write("<div class=\"team\">\r\n");
      out.write("\t <div class=\"container\">\r\n");
      out.write("\t\t\t<h3>团队精英</h3>\r\n");
      out.write("\t\t\t<div class=\"team-info\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 team-grids\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-responsive\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/members/1.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"captn\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>刘立彬</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Aenean pulvinar ac enimet posuere tincidunt velit Utin tincidunt</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 team-grids\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-responsive\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/members/2.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"captn\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>杨雨</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Aenean pulvinar ac enimet posuere tincidunt velit Utin tincidunt</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 team-grids\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-responsive\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/members/3.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"captn\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>王申卿</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Aenean pulvinar ac enimet posuere tincidunt velit Utin tincidunt</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\" style=\"padding:10px 0;\"> </div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 team-grids\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-responsive\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/members/4.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"captn\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>张玉超</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Aenean pulvinar ac enimet posuere tincidunt velit Utin tincidunt</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 team-grids\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-responsive\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/frontimg/members/5.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"captn\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>吴淼</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Aenean pulvinar ac enimet posuere tincidunt velit Utin tincidunt</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!---->\r\n");
      out.write("<div id=\"contact\" class=\"contact\">\r\n");
      out.write("\t    <!--<h3>联系我们</h3>\t\t-->\r\n");
      out.write("\t <div class=\"container\">\r\n");
      out.write("\t <div class=\"contact-grids\">\r\n");
      out.write("\t\t <div class=\"contact-icons\">\r\n");
      out.write("\t\t\t\t<div class=\"contact-grid\">\r\n");
      out.write("\t\t\t\t\t<div class=\"contact-fig\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-phone fa-lg\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p>18525511611</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"contact-grid\">\r\n");
      out.write("\t\t\t\t\t<div class=\"contact-fig1\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-map-marker fa-lg\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p>辽宁省大连市甘井子区大连市甘井子区\r\n");
      out.write("\t\t\t\t\t\t<span>黄浦路537号泰德大厦07屋08A单元</span></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"contact-grid\">\r\n");
      out.write("\t\t\t\t\t<div class=\"contact-fig2\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-envelope fa-lg\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p><a href=\"mailto:info@example.com\">example@mail.com</a></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t\t<!-- <iframe width=\"504\" height=\"781\" frameborder=\"0\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\" src=\"http://j.map.baidu.com/wWbAL\"></iframe> -->\r\n");
      out.write("\t\t\t<!--  <form>\r\n");
      out.write("\t\t\t\t<input type=\"text\" placeholder=\"Name\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" placeholder=\"Email\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" placeholder=\"Website\">\r\n");
      out.write("\t\t\t\t<textarea placeholder=\"Message...\"></textarea>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"SEND\">\r\n");
      out.write("\t\t\t </form> -->\r\n");
      out.write("\t\t\t </div>\t\t\t \r\n");
      out.write("\t </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!---->\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t <div class=\"container\">\r\n");
      out.write("\t\t <div class=\"copywrite\">\r\n");
      out.write("\t\t\t <p>Copyright &copy; 2017.大连意匠装修工程有限公司 </p>\r\n");
      out.write("\t\t </div>\t\t \r\n");
      out.write("\t </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!---->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/frontjs/move-top.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/frontjs/easing.js\"></script>\r\n");
      out.write("<!-- banner 滑动 -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/silder/wySilder.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/components/dist/scripts/modernizr-chrg.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/components/dist/scripts/imagesloaded.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/components/dist/scripts/masonry.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourcesUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/components/dist/scripts/chromagallery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Start gallery  -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("\t\t\t$(\".mygallery\").chromaGallery\r\n");
      out.write("\t\t    ({\r\n");
      out.write("\t\t        color:'#000',\r\n");
      out.write("\t\t        gridMargin:15,\r\n");
      out.write("\t\t        maxColumns:5,\r\n");
      out.write("\t\t        dof:true,\r\n");
      out.write("\t\t        screenOpacity:0.8\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- Begin gallery -->\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function (){\r\n");
      out.write("\t\t$(\".js-silder\").silder({\r\n");
      out.write("            auto: true,//自动播放，传入任何可以转化为true的值都会自动轮播\r\n");
      out.write("            speed: 25,//轮播图运动速度\r\n");
      out.write("            sideCtrl: true,//是否需要侧边控制按钮\r\n");
      out.write("            defaultView: 0,//默认显示的索引\r\n");
      out.write("            interval: 3000,//自动轮播的时间，以毫秒为单位，默认3000毫秒\r\n");
      out.write("            activeClass: \"active\",//小的控制按钮激活的样式，不包括作用两边，默认active\r\n");
      out.write("        });\r\n");
      out.write("\t});\r\n");
      out.write(" </script>\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("\t\tjQuery(document).ready(function($) {\r\n");
      out.write("\t\t\t$(\".scroll\").click(function(event){\t\t\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\t$('html,body').animate({scrollTop:$(this.hash).offset().top},1200);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<!---->\r\n");
      out.write("<!--script-->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\t/*\r\n");
      out.write("\t\t\t\tvar defaults = {\r\n");
      out.write("\t\t\t\tcontainerID: 'toTop', // fading element id\r\n");
      out.write("\t\t\t\tcontainerHoverID: 'toTopHover', // fading element hover id\r\n");
      out.write("\t\t\t\tscrollSpeed: 1200,\r\n");
      out.write("\t\t\t\teasingType: 'linear' \r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\t*/\r\n");
      out.write("\t\t\t$().UItoTop({ easingType: 'easeOutQuart' });\r\n");
      out.write("\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<a href=\"#to-top\" id=\"toTop\" style=\"display: block;\"> <span id=\"toTopHover\" style=\"opacity: 1;\"> </span></a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
